description: '`global` `{{theme_settings}}` object'
type: object
properties:
  alert-backgroundColor:
    type: string
  alert-color:
    type: string
  alert-color-alt:
    type: string
  applePay-button:
    type: string
  blockquote-cite-font-color:
    type: string
  blog_size:
    type: string
  body-bg:
    type: string
  body-font:
    type: string
  brand_size:
    type: string
  brandpage_products_per_page:
    type: integer
  button--default-borderColor:
    type: string
  button--default-borderColorActive:
    type: string
  button--default-borderColorHover:
    type: string
  button--default-color:
    type: string
  button--default-colorActive:
    type: string
  button--default-colorHover:
    type: string
  button--disabled-backgroundColor:
    type: string
  button--disabled-borderColor:
    type: string
  button--disabled-color:
    type: string
  button--icon-svg-color:
    type: string
  button--primary-backgroundColor:
    type: string
  button--primary-backgroundColorActive:
    type: string
  button--primary-backgroundColorHover:
    type: string
  button--primary-color:
    type: string
  button--primary-colorActive:
    type: string
  button--primary-colorHover:
    type: string
  card--alternate-backgroundColor:
    type: string
  card--alternate-borderColor:
    type: string
  card--alternate-color--hover:
    type: string
  card-figcaption-button-background:
    type: string
  card-figcaption-button-color:
    type: string
  card-title-color:
    type: string
  card-title-color-hover:
    type: string
  carousel-arrow-bgColor:
    type: string
  carousel-arrow-borderColor:
    type: string
  carousel-arrow-color:
    type: string
  carousel-bgColor:
    type: string
  carousel-description-color:
    type: string
  carousel-dot-bgColor:
    type: string
  carousel-dot-color:
    type: string
  carousel-dot-color-active:
    type: string
  carousel-title-color:
    type: string
  categorypage_products_per_page:
    type: integer
  checkRadio-backgroundColor:
    type: string
  checkRadio-borderColor:
    type: string
  checkRadio-color:
    type: string
  color-black:
    type: string
  color-error:
    type: string
  color-errorLight:
    type: string
  color-grey:
    type: string
  color-greyDark:
    type: string
  color-greyDarker:
    type: string
  color-greyDarkest:
    type: string
  color-greyLight:
    type: string
  color-greyLighter:
    type: string
  color-greyLightest:
    type: string
  color-greyMedium:
    type: string
  color-info:
    type: string
  color-infoLight:
    type: string
  color-primary:
    type: string
  color-primaryDark:
    type: string
  color-primaryDarker:
    type: string
  color-primaryLight:
    type: string
  color-secondary:
    type: string
  color-secondaryDark:
    type: string
  color-secondaryDarker:
    type: string
  color-success:
    type: string
  color-successLight:
    type: string
  color-textBase:
    type: string
  color-textBase--active:
    type: string
  color-textBase--hover:
    type: string
  color-textHeading:
    type: string
  color-textLink:
    type: string
  color-textLink--active:
    type: string
  color-textLink--hover:
    type: string
  color-textSecondary:
    type: string
  color-textSecondary--active:
    type: string
  color-textSecondary--hover:
    type: string
  color-warning:
    type: string
  color-warningLight:
    type: string
  color-white:
    type: string
  color-whitesBase:
    type: string
  color_badge_product_sale_badges:
    type: string
  color_hover_product_sale_badges:
    type: string
  color_text_product_sale_badges:
    type: string
  container-border-global-color-base:
    type: string
  container-fill-base:
    type: string
  container-fill-dark:
    type: string
  default_image_brand:
    type: string
  default_image_gift_certificate:
    type: string
  default_image_product:
    type: string
  dropdown--quickSearch-backgroundColor:
    type: string
  dropdown--wishList-backgroundColor:
    type: string
  fontSize-h1:
    type: integer
  fontSize-h2:
    type: integer
  fontSize-h3:
    type: integer
  fontSize-h4:
    type: integer
  fontSize-h5:
    type: integer
  fontSize-h6:
    type: integer
  fontSize-root:
    type: integer
  footer-backgroundColor:
    type: string
  form-label-font-color:
    type: string
  gallery_size:
    type: string
  geotrust_ssl_common_name:
    type: string
  geotrust_ssl_seal_size:
    type: string
  header-backgroundColor:
    type: string
  headings-font:
    type: string
  hide_blog_page_heading:
    type: boolean
  hide_breadcrumbs:
    type: boolean
  hide_category_page_heading:
    type: boolean
  hide_contact_us_page_heading:
    type: boolean
  hide_content_navigation:
    type: boolean
  hide_page_heading:
    type: boolean
  homepage_blog_posts_count:
    type: integer
  homepage_featured_products_column_count:
    type: integer
  homepage_featured_products_count:
    type: integer
  homepage_new_products_column_count:
    type: integer
  homepage_new_products_count:
    type: integer
  homepage_show_carousel:
    type: boolean
  homepage_show_carousel_arrows:
    type: boolean
  homepage_stretch_carousel_images:
    type: boolean
  homepage_top_products_column_count:
    type: integer
  homepage_top_products_count:
    type: integer
  icon-color:
    type: string
  icon-color-hover:
    type: string
  icon-ratingEmpty:
    type: string
  icon-ratingFull:
    type: string
  input-bg-color:
    type: string
  input-border-color:
    type: string
  input-border-color-active:
    type: string
  input-disabled-bg:
    type: string
  input-font-color:
    type: string
  label-backgroundColor:
    type: string
  label-color:
    type: string
  loadingOverlay-backgroundColor:
    type: string
  logo-position:
    type: string
  logo_fontSize:
    type: integer
  logo_size:
    type: string
  navPages-color:
    type: string
  navPages-color-hover:
    type: string
  navPages-subMenu-backgroundColor:
    type: string
  navPages-subMenu-separatorColor:
    type: string
  navUser-color:
    type: string
  navUser-color-hover:
    type: string
  navUser-dropdown-backgroundColor:
    type: string
  navUser-dropdown-borderColor:
    type: string
  navUser-indicator-backgroundColor:
    type: string
  navigation_design:
    type: string
  optimizedCheckout-backgroundImage:
    type: string
  optimizedCheckout-backgroundImage-size:
    type: string
  optimizedCheckout-body-backgroundColor:
    type: string
  optimizedCheckout-buttonPrimary-backgroundColor:
    type: string
  optimizedCheckout-buttonPrimary-backgroundColorActive:
    type: string
  optimizedCheckout-buttonPrimary-backgroundColorDisabled:
    type: string
  optimizedCheckout-buttonPrimary-backgroundColorHover:
    type: string
  optimizedCheckout-buttonPrimary-borderColor:
    type: string
  optimizedCheckout-buttonPrimary-borderColorActive:
    type: string
  optimizedCheckout-buttonPrimary-borderColorDisabled:
    type: string
  optimizedCheckout-buttonPrimary-borderColorHover:
    type: string
  optimizedCheckout-buttonPrimary-color:
    type: string
  optimizedCheckout-buttonPrimary-colorActive:
    type: string
  optimizedCheckout-buttonPrimary-colorDisabled:
    type: string
  optimizedCheckout-buttonPrimary-colorHover:
    type: string
  optimizedCheckout-buttonPrimary-font:
    type: string
  optimizedCheckout-buttonSecondary-backgroundColor:
    type: string
  optimizedCheckout-buttonSecondary-backgroundColorActive:
    type: string
  optimizedCheckout-buttonSecondary-backgroundColorHover:
    type: string
  optimizedCheckout-buttonSecondary-borderColor:
    type: string
  optimizedCheckout-buttonSecondary-borderColorActive:
    type: string
  optimizedCheckout-buttonSecondary-borderColorHover:
    type: string
  optimizedCheckout-buttonSecondary-color:
    type: string
  optimizedCheckout-buttonSecondary-colorActive:
    type: string
  optimizedCheckout-buttonSecondary-colorHover:
    type: string
  optimizedCheckout-buttonSecondary-font:
    type: string
  optimizedCheckout-colorFocus:
    type: string
  optimizedCheckout-contentPrimary-color:
    type: string
  optimizedCheckout-contentPrimary-font:
    type: string
  optimizedCheckout-contentSecondary-color:
    type: string
  optimizedCheckout-contentSecondary-font:
    type: string
  optimizedCheckout-discountBanner-backgroundColor:
    type: string
  optimizedCheckout-discountBanner-iconColor:
    type: string
  optimizedCheckout-discountBanner-textColor:
    type: string
  optimizedCheckout-form-textColor:
    type: string
  optimizedCheckout-formChecklist-backgroundColor:
    type: string
  optimizedCheckout-formChecklist-backgroundColorSelected:
    type: string
  optimizedCheckout-formChecklist-borderColor:
    type: string
  optimizedCheckout-formChecklist-color:
    type: string
  optimizedCheckout-formField-backgroundColor:
    type: string
  optimizedCheckout-formField-borderColor:
    type: string
  optimizedCheckout-formField-errorColor:
    type: string
  optimizedCheckout-formField-inputControlColor:
    type: string
  optimizedCheckout-formField-placeholderColor:
    type: string
  optimizedCheckout-formField-shadowColor:
    type: string
  optimizedCheckout-formField-textColor:
    type: string
  optimizedCheckout-header-backgroundColor:
    type: string
  optimizedCheckout-header-borderColor:
    type: string
  optimizedCheckout-header-textColor:
    type: string
  optimizedCheckout-headingPrimary-color:
    type: string
  optimizedCheckout-headingPrimary-font:
    type: string
  optimizedCheckout-headingSecondary-color:
    type: string
  optimizedCheckout-headingSecondary-font:
    type: string
  optimizedCheckout-link-color:
    type: string
  optimizedCheckout-link-font:
    type: string
  optimizedCheckout-link-hoverColor:
    type: string
  optimizedCheckout-loadingToaster-backgroundColor:
    type: string
  optimizedCheckout-loadingToaster-textColor:
    type: string
  optimizedCheckout-logo:
    type: string
  optimizedCheckout-logo-position:
    type: string
  optimizedCheckout-logo-size:
    type: string
  optimizedCheckout-orderSummary-backgroundColor:
    type: string
  optimizedCheckout-orderSummary-borderColor:
    type: string
  optimizedCheckout-show-backgroundImage:
    type: boolean
  optimizedCheckout-show-logo:
    type: string
  optimizedCheckout-step-backgroundColor:
    type: string
  optimizedCheckout-step-borderColor:
    type: string
  optimizedCheckout-step-textColor:
    type: string
  overlay-backgroundColor:
    type: string
  pace-progress-backgroundColor:
    type: string
  paymentbuttons-paypal-color:
    type: string
  paymentbuttons-paypal-fundingicons:
    type: boolean
  paymentbuttons-paypal-label:
    type: string
  paymentbuttons-paypal-layout:
    type: string
  paymentbuttons-paypal-shape:
    type: string
  paymentbuttons-paypal-size:
    type: string
  paymentbuttons-paypal-tagline:
    type: boolean
  pdp-custom-fields-tab-label:
    type: string
  pdp-non-sale-price-label:
    type: string
  pdp-price-label:
    type: string
  pdp-retail-price-label:
    type: string
  pdp-sale-price-label:
    type: string
  price_ranges:
    type: boolean
  product_list_display_mode:
    type: string
  product_sale_badges:
    type: string
  product_size:
    type: string
  productgallery_size:
    type: string
  productpage_related_products_count:
    type: integer
  productpage_reviews_count:
    type: integer
  productpage_similar_by_views_count:
    type: integer
  productpage_videos_count:
    type: integer
  productthumb_size:
    type: string
  productview_thumb_size:
    type: string
  restrict_to_login:
    type: boolean
  searchpage_products_per_page:
    type: integer
  select-arrow-color:
    type: string
  select-bg-color:
    type: string
  shop_by_brand_show_footer:
    type: boolean
  shop_by_price_visibility:
    type: boolean
  show_accept_amex:
    type: boolean
  show_accept_discover:
    type: boolean
  show_accept_mastercard:
    type: boolean
  show_accept_paypal:
    type: boolean
  show_accept_visa:
    type: boolean
  show_copyright_footer:
    type: boolean
  show_custom_fields_tabs:
    type: boolean
  show_powered_by:
    type: boolean
  show_product_details_tabs:
    type: boolean
  show_product_dimensions:
    type: boolean
  show_product_quantity_box:
    type: boolean
  show_product_quick_view:
    type: boolean
  show_product_reviews_tabs:
    type: boolean
  show_product_weight:
    type: boolean
  social_icon_placement_bottom:
    type: string
  social_icon_placement_top:
    type: boolean
  spinner-borderColor-dark:
    type: string
  spinner-borderColor-light:
    type: string
  storeName-color:
    type: string
  supported_card_type_icons:
    type: array
    items:
      type: string
  swatch_option_size:
    type: string
  thumb_size:
    type: string
  zoom_size:
    type: string
